---
- name: ansible-playbook
  hosts: ansible_clients
  become: true

  tasks:
   - name: install nginx
     apt:
       name: nginx
       state: latest
   - name: run nginx
     service:
       name: nginx
       state: started
   - name: create content
     copy:
       content: "I was configured through Ansible"
       dest: /var/www/html/index.html
